# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- destroy

pool: default


stages:
  - stage:
    jobs:
      - job:
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Azure- pass subscription'
            backendAzureRmResourceGroupName: 'NetworkWatcherRG'
            backendAzureRmStorageAccountName: 'terraformstate2011'
            backendAzureRmContainerName: 'tfstatefiles'
            backendAzureRmKey: 'tfstate'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'destroy'
            environmentServiceNameAzureRM: 'Azure- pass subscription'

